export const ADMIN_SCHEDULE_TILE_BACKGROUND = '#F2FFF3';
export const ADMIN_SCHEDULE_DIVIDER_COLOR = '#96BE8C';
export const ADMIN_SCHEDULE_LABEL_COLOR = '#243119';
export const ADMIN_SCHEDULE_TIME_CHIP_BACKGROUND = '#E8F4FC';
export const ADMIN_SCHEDULE_TIME_CHIP_TEXT = '#007AFF';
export const ADMIN_SCHEDULE_REMOVE_BACKGROUND = '#FFF0F0';
export const ADMIN_SCHEDULE_REMOVE_BORDER = '#FF616D';
export const ADMIN_SCHEDULE_REMOVE_TEXT = '#FF616D';
