export const SCHEDULE_CONTENT_HORIZONTAL = 20;
export const SCHEDULE_TIMELINE_LEFT = 34;
export const SCHEDULE_TIMELINE_X =
  SCHEDULE_TIMELINE_LEFT - SCHEDULE_CONTENT_HORIZONTAL;

export const SCHEDULE_TIMELINE_COLOR = '#B8B8B8';
export const SCHEDULE_TIMELINE_DASH = '4 4';
